### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by FranciscoMiguel30** [UseKamba/dev-intern-mobile-backend-frontend-web#1]
Tenho dúvidas em fazer Pull Request

**Comment by amarildolucas** [comment]
Olá @FranciscoMiguel30, envie-nos o .Zip do Projeto diretamente para o nosso E-mail *info@usekamba.com*.  Nomeie como *FranciscoMiguelIntern.zip*

Ficamos aguardando!

**Comment by amarildolucas** [comment]
Sim! Para os demais que estiverem com o mesmo problema, podem seguir à instrução acima. Nosso e-mail novamente: info@usekamba.com

**Comment by amarildolucas** [comment]
Notei que ambos enviaram o .zip, sendo assim, estou fechando está issue.
