### ISSUE TITLE
Solicitação para o aumento de saldo na conta da API

### ISSUE THREAD

**Issue by GarciaFreelancer** [UseKamba/dev-intern-mobile-backend-frontend-web#3]
Ao realizar a solicitação do tipo POST para a API de teste retorna o resultado em JSON, porém dizendo "Dados inválidos" e que a transacção não pode ser superior ao saldo na conta. Fui reduzindo o valor das transacções até 1, porém o resultado continua o mesmo. Mas ao inserir um valor inferior a 1 a mensagem muda para a transacção "não pode ser inferior à 1,00 Kz". Resumindo, essa situação leva-me a crer que a conta já não possui saldo. Desta feita solicito-os para aumentarem o saldo na conta de exemplo da API, para que deste modo possa ser possível realizar o teste com forme o esperado.

Aguardo pela vossa resposta

**Comment by amarildolucas** [comment]
Olá Garcia, algum dos Interns estava com um erro que deixou as transações em loop então zeramos a conta até que no caso fosse corrigido o erro. Mas já foi resolvido faz um tempo. Se tentar agora provavelmente estará funcionando normalmente.

**Comment by amarildolucas** [comment]
Notei que o problema foi resolvido. Sendo assim, estou fechando esta issue.
